### ISSUE TITLE
[BUG] Patcher doesn't work while imported

### ISSUE THREAD

**Issue by h4-h** [Neodymium7/BundleBD#6]
### Before Reporting...

- [x] I have searched the existing issues and can confirm that a similar report has not already been submitted.
- [X] I have consulted the [Wiki](https://github.com/Neodymium7/BundleBD/wiki) and [FAQ](https://github.com/Neodymium7/BundleBD/wiki/FAQ) to see if my issue was already addressed.

### Issue Description

I think it's because of creating a new instance of BdApi, if you replace it in the output file with `const betterdiscord = BdApi;` all works.

### Steps to Reproduce

```js
import { Patcher } from "betterdiscord";

Patcher.before("name", Module, "function", (_, args, origin) => { console.log(args) });
```

**Comment by Neodymium7** [comment]
With a bound instance of BdApi, Patcher methods do not take a “name” argument. Does that fix your issue?
